namespace: "jfrog"
name: "installers"
version: "1.1.3"
description: "Ansible roles for jfrog software installation"

repository: "https://github.com/jfrog/JFrog-Cloud-Installers"
documentation: "https://github.com/jfrog/JFrog-Cloud-Installers/blob/master/Ansible/README.md"
homepage: "https://github.com/jfrog/JFrog-Cloud-Installers/tree/master/Ansiblea"
issues: "https://github.com/jfrog/JFrog-Cloud-Installers/issues"

readme: "README.md"


dependencies:
